name: 'Git Version'
description: 'Retrieve the GitVersion output'
inputs:
  args:  # id of input
    description: 'GitVersion Arguments'
    required: false
    default: ''
outputs:
  fullsemver: # id of output
    description: 'Full SemVer discovered by GitVersion'
runs:
  using: 'node12'
  main: 'index.js'
