name: 'Git Version'
description: 'Retrieve the GitVersion output'
inputs:
  args:  # id of input
    description: 'GitVersion Arguments'
    required: false
    default: ''
  ref:
    description: 'Branch from which event is triggered from - will be checked out to get history'
    required: true
    default: ''
  sha:
    description: 'Commit id to checkout'
    required: true
    default: ''
outputs:
  major:
    description: 'Major version number'
  minor:
    description: 'Minor version number'
  patch:
    description: 'Patch number'
  build:
    description: 'Build number'
  semver:
    description: 'Semantic version number'
  fullsemver: # id of output
    description: 'Full SemVer discovered by GitVersion'
  assemblysemver:
    description: 'Assembly SemVer'
  gitversion:
    description: 'Full GitVersion response'
  nugetversion:
    description: 'Nuget Version'
runs:
  using: 'node12'
  main: 'index.js'
